name: Run-tests
on:
  repository_dispatch:
    types: 
      - build

jobs:
  build:
    name: This is from curl requests
    runs-on: ubuntu-latest
    env:
      GITHUB_CONTEXT: ${{ toJson(github) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Send slack message
        run: |
          python3 $GITHUB_WORKSPACE/.github/workflows/files/riseup.py
        env:
          REPO_NAME: ${{ github.repository }}
          REVIEWER: ${{ github.actor }}
          DESCRIPTION: ${{ github.event.client_payload.description }}
          LINK_TO_PR: ${{ github.event.client_payload.link_to_pr }}
